# Generated by Django 5.1.6 on 2025-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChainAPI', '0002_alter_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_input', models.TextField()),
                ('staff_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
